@baseUrl = http://localhost:4000/api
@token = <paste_token_here>
@taskId = <paste_task_id_here>

### Get all tasks
GET {{baseUrl}}/tasks
Authorization: Bearer {{token}}

### Get all tasks filtered by status
GET {{baseUrl}}/tasks?status=todo
Authorization: Bearer {{token}}

### Get all tasks filtered by priority
GET {{baseUrl}}/tasks?priority=high
Authorization: Bearer {{token}}

### Get all tasks filtered by status and priority
GET {{baseUrl}}/tasks?status=done&priority=high
Authorization: Bearer {{token}}

### Get task by ID
GET {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}

### Create task
POST {{baseUrl}}/tasks
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "title": "My new task",
  "description": "Task description",
  "dueDate": "2026-05-01",
  "priority": "high",
  "status": "todo"
}

### Update task
PATCH {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "in-progress",
  "priority": "medium"
}

### Delete task
DELETE {{baseUrl}}/tasks/{{taskId}}
Authorization: Bearer {{token}}
